variable environment {}
variable region {}
variable account_number {}
variable contact {}
variable product {}
variable sub_product {}
variable cost_code {}
variable orchestration {}
variable distribution_bucket {}
